# Generated by Django 5.0.6 on 2024-05-27 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentDateTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(unique=True)),
                ('end_time', models.TimeField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HealthCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id_number', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('identity_type', models.CharField(choices=[('nrc', 'National Registration Card'), ('passport', 'Passport')], default='nrc', max_length=30)),
                ('identity_number', models.CharField(max_length=50, unique=True)),
                ('occupation', models.CharField(max_length=100)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('civil_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.maritalstatus')),
                ('title_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.usertitle')),
            ],
        ),
        migrations.CreateModel(
            name='ContactInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number_1', models.CharField(max_length=20)),
                ('phone_number_2', models.CharField(blank=True, max_length=20, null=True)),
                ('address_1', models.CharField(max_length=255)),
                ('address_2', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=50)),
                ('province', models.CharField(max_length=100)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.country')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact_info', to='patient_management.patient')),
            ],
        ),
        migrations.CreateModel(
            name='PatientHealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergies', models.TextField()),
                ('medical_history', models.TextField()),
                ('surgical_history', models.TextField()),
                ('medication', models.TextField()),
                ('paiient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_health_record', to='patient_management.patient')),
            ],
        ),
        migrations.CreateModel(
            name='PrimaryContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('relationship', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=20)),
                ('identity_type', models.CharField(choices=[('nrc', 'National Registration Card'), ('passport', 'Passport')], default='nrc', max_length=50)),
                ('identity_number', models.CharField(max_length=50, unique=True)),
                ('address_1', models.CharField(max_length=255)),
                ('address_2', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=50)),
                ('province', models.CharField(max_length=100)),
                ('country', models.CharField(default='Zambia', max_length=100)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_contact', to='patient_management.patient')),
                ('title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.usertitle')),
            ],
        ),
        migrations.CreateModel(
            name='RiskFactors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health_conditions', models.CharField(max_length=100)),
                ('smoking_status', models.CharField(choices=[('never', 'Never'), ('former', 'Former'), ('current', 'Current')], max_length=20)),
                ('smoking_status_description', models.TextField(blank=True, null=True)),
                ('alcohol_use', models.CharField(choices=[('never', 'Never'), ('occasional', 'Occasional'), ('regular', 'Regular')], max_length=20)),
                ('alcohol_use_description', models.TextField(blank=True, null=True)),
                ('paiient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_factors', to='patient_management.patient')),
            ],
        ),
    ]
