# Generated by Django 5.0.6 on 2024-05-27 07:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField(blank=True, null=True)),
                ('appointment_reason', models.TextField(max_length=100)),
                ('scheduler', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Checked-In', 'Checked-In'), ('PRN', 'PRN')], default='Active', max_length=50)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('end_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments_end', to='patient_management.appointmentdatetime')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patient_management.patient')),
                ('start_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments_start', to='patient_management.appointmentdatetime')),
            ],
        ),
    ]
