# Generated by Django 5.0.6 on 2024-05-28 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_management', '0002_appointments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointmentdatetime',
            old_name='end_time',
            new_name='appointment_time',
        ),
        migrations.RemoveField(
            model_name='appointmentdatetime',
            name='start_time',
        ),
        migrations.AlterField(
            model_name='appointments',
            name='appointment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
    ]
