# Generated by Django 5.0.6 on 2024-05-30 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_management', '0003_rename_end_time_appointmentdatetime_appointment_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Checked-In', 'Checked-In'), ('PRN', 'PRN'), ('Reschedule', 'Reschedule')], default='Active', max_length=50),
        ),
    ]
