# Generated by Django 5.0.6 on 2024-05-31 08:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_management', '0006_alter_vitals_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vitals',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
    ]
