# Generated by Django 5.0.6 on 2024-06-04 11:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_management', '0008_diagnosis'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='vitals',
            name='bp',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vitals',
            name='height',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vitals',
            name='pulseRate',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vitals',
            name='respiration',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vitals',
            name='temperature',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vitals',
            name='weight',
            field=models.IntegerField(),
        ),
    ]
