# Generated by Django 5.0.6 on 2024-06-04 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_management', '0009_diagnosis_date_alter_vitals_bp_alter_vitals_height_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patienthealthrecord',
            old_name='paiient',
            new_name='patient',
        ),
        migrations.AddField(
            model_name='patienthealthrecord',
            name='family_history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patienthealthrecord',
            name='personal_history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patienthealthrecord',
            name='social_history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patienthealthrecord',
            name='warnings',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patienthealthrecord',
            name='allergies',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patienthealthrecord',
            name='medical_history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patienthealthrecord',
            name='medication',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patienthealthrecord',
            name='surgical_history',
            field=models.TextField(blank=True, null=True),
        ),
    ]
