# Generated by Django 5.0.6 on 2024-06-06 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_management', '0010_rename_paiient_patienthealthrecord_patient_and_more'),
        ('users', '0012_remove_medicine_advice_remove_medicine_days_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine_prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.IntegerField(blank=True, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('instruction', models.TextField(blank=True, null=True)),
                ('advice', models.TextField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.medicine_category')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.medicine')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient_management.patient')),
            ],
        ),
    ]
