# Generated by Django 5.0.6 on 2024-06-06 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_management', '0013_checkin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CheckIn',
        ),
    ]
