# Generated by Django 5.0.6 on 2024-06-06 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_management', '0016_alter_checkin_checkin_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkin',
            name='vitals',
        ),
        migrations.AddField(
            model_name='vitals',
            name='checkin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patient_management.checkin'),
        ),
    ]
