# Generated by Django 5.0.6 on 2024-06-06 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_management', '0017_remove_checkin_vitals_vitals_checkin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkin',
            name='diagnosis',
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='checkin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patient_management.checkin'),
        ),
    ]
