# Generated by Django 5.0.6 on 2024-06-06 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_management', '0018_remove_checkin_diagnosis_diagnosis_checkin'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine_prescription',
            name='checkin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patient_management.checkin'),
        ),
    ]
