# Generated by Django 5.0.6 on 2024-06-07 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_management', '0019_medicine_prescription_checkin'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='status',
            field=models.CharField(choices=[('CheckIN', 'CheckIN'), ('CheckOut', 'CheckOut')], default='Active', max_length=50),
        ),
    ]
