# Generated by Django 5.0.6 on 2024-06-07 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_management', '0020_checkin_status'),
        ('users', '0014_alter_myuser_phone_number_1_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='department',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='users.department'),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='staff',
            field=models.ForeignKey(blank=True, limit_choices_to={'designation': '1'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='status',
            field=models.CharField(choices=[('Checked in', 'Checked in'), ('Collect Vitals', 'Collect Vitals'), ('Perform diagnosis', 'Perform diagnosis'), ('Nurse', 'Nurse'), ('Doctor', 'Doctor'), ('Complete', 'Complete')], default='Checked in', max_length=50),
        ),
    ]
