# Generated by Django 5.0.6 on 2024-06-10 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_management', '0021_alter_checkin_department_alter_checkin_staff_and_more'),
        ('users', '0015_rename_costdef_services_disc_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine_prescription',
            name='drug',
            field=models.ManyToManyField(to='users.inventory_list'),
        ),
    ]
