# Generated by Django 5.0.6 on 2024-06-10 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_management', '0022_medicine_prescription_drug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine_prescription',
            old_name='drug',
            new_name='prescribed',
        ),
    ]
