# Generated by Django 5.0.6 on 2024-06-12 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_management', '0023_rename_drug_medicine_prescription_prescribed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkin',
            name='medication',
        ),
        migrations.RemoveField(
            model_name='medicine_prescription',
            name='category',
        ),
        migrations.RemoveField(
            model_name='medicine_prescription',
            name='drug_name',
        ),
    ]
