# Generated by Django 5.0.6 on 2024-06-12 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_management', '0025_rename_checkin_medicine_prescription_checkin_record_and_more'),
        ('users', '0015_rename_costdef_services_disc_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkin',
            name='medication',
        ),
        migrations.AlterField(
            model_name='medicine_prescription',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patient_management.patient'),
        ),
        migrations.AlterField(
            model_name='medicine_prescription',
            name='prescribed',
            field=models.ManyToManyField(blank=True, to='users.inventory_list'),
        ),
        migrations.AddField(
            model_name='checkin',
            name='medication',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='patient_management.medicine_prescription'),
            preserve_default=False,
        ),
    ]
