# Generated by Django 5.0.6 on 2024-06-12 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_management', '0026_remove_checkin_medication_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkin',
            name='medication',
        ),
        migrations.AddField(
            model_name='checkin',
            name='medication',
            field=models.ManyToManyField(blank=True, related_name='checkins', to='patient_management.medicine_prescription'),
        ),
    ]
