# Generated by Django 5.0.6 on 2024-06-14 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_management', '0028_remove_medicine_prescription_prescribed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine_prescription',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
