# Generated by Django 5.0.6 on 2024-08-22 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_management', '0030_alter_checkin_department_alter_checkin_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='identity_type',
            field=models.CharField(choices=[('nrc', 'National Registration Card'), ('passport', 'Passport')], default='NRC', max_length=30),
        ),
    ]
