# Generated by Django 5.0.6 on 2024-08-22 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_management', '0031_alter_patient_identity_type'),
        ('users', '0022_myuser_attention'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='status',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='users.status'),
        ),
    ]
