# Generated by Django 5.0.6 on 2024-06-06 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_inventory_list'),
    ]

    operations = [
        migrations.DeleteModel(
            name='inventory_List',
        ),
    ]
