# Generated by Django 5.0.6 on 2024-06-06 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_delete_inventory_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='inventory_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=255)),
                ('quantity_in', models.IntegerField()),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('quantity_out', models.IntegerField(blank=True, null=True)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Quantity_Bal', models.IntegerField(blank=True, null=True)),
                ('book_Bal', models.DecimalField(decimal_places=2, max_digits=6)),
                ('barcode', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('inactive', 'inactive')], default='Active', max_length=255)),
                ('Inventory_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.inventory')),
            ],
        ),
    ]
