# Generated by Django 5.0.6 on 2024-06-06 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_inventory_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory_list',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
            preserve_default=False,
        ),
    ]
