# Generated by Django 5.0.6 on 2024-06-06 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_services_category_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='advice',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='days',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='instruction',
        ),
    ]
