# Generated by Django 5.0.6 on 2024-06-06 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_medicine_advice_remove_medicine_days_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='name',
            new_name='drug_name',
        ),
    ]
