# Generated by Django 5.0.6 on 2024-06-07 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_rename_name_medicine_drug_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='phone_number_1',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='phone_number_2',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
