# Generated by Django 5.0.6 on 2024-06-10 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_myuser_phone_number_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='costdef',
            new_name='disc_amount',
        ),
    ]
