# Generated by Django 5.0.6 on 2024-06-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_rename_costdef_services_disc_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='vat',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
