# Generated by Django 5.0.6 on 2024-06-17 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_company_vat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='vat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
