# Generated by Django 5.0.6 on 2024-08-22 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='category',
            field=models.CharField(max_length=100),
        ),
    ]
