# Generated by Django 5.0.6 on 2024-08-22 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_status_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='attention',
            field=models.ManyToManyField(blank=True, to='users.status'),
        ),
    ]
